In [1]:
x = np.array([10, 11, 12, 13, 14])
y = np.array([0, 1, 2, 3, 4])

In [2]:
x+y

array([10, 12, 14, 16, 18])

In [3]:
x-y

array([10, 10, 10, 10, 10])

In [5]:
np.array([[5, 6], [7, 8]]) + np.array([[10, 20],[30, 40]]) - np.array([[1, 2],[3, 4]])

array([[14, 24],
       [34, 44]])

In [7]:
x = np.array([[1], [2], [3]])
y = np.array([[4], [5], [6]])

x.T@y

array([[32]])

In [8]:
np.dot(x.T, y)

array([[32]])

In [9]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [10]:
np.dot(x.T, y)

32